camel-tooling/vscode-wsdl2rest

.gitignore
.travis.yml
Readme.md
package-lock.json
package.json
simplews/manualstart.js
src/extension.ts
src/test/address.wsdl
src/test/app_soap.js
src/test/helloworld.wsdl
src/test/wsdl2rest_tests.ts
tsconfig.json
wsdl2rest/config/logging.properties
wsdl2rest/pom.xml

First cut at running wsdl2rest in java thru extension

---

package.json
simplews/manualstart.js
simplews/manualstart.ts
simplews/readme.md
src/extension.ts
src/test/extension.test.ts
src/test/wsdl_file.test.ts
src/test/wsdl_url.test.ts

issue #8 - adding wsdl url capability and test

---

src/extension.ts
src/test/wsdl_url.test.ts
src/utils.ts

Signed-off-by: Brian Fitzpatrick [bfitzpat@redhat.com](mailto:bfitzpat@redhat.com)

Issue10 validate inputs

---

src/extension.ts
src/test/wsdl_file.test.ts
src/test/wsdl_url.test.ts
src/utils.ts

issue #16 - fixing tests and addressing root directory issue

---

src/test/test_utils.ts
src/test/wsdl_file.test.ts
src/test/wsdl_url.test.ts
src/utils.ts

issue #16 - cleaning up test code

---

.travis.yml

issue #12 - enabling the deploy task on travis

---

.travis.yml

issue #12 - adding missing vsce lines to travis script

---

package.json

issue #12 - updating version to 0.0.2

---

package.json

issue #12 - last tweak to update version to 0.0.3 for release

---

package.json

issue #12 - fixing license issue and updating version again to 0.0.4

---

.vscodeignore
sonar-project.properties

to test locally.
- launch a [Sonar local instance](https://docs.sonarqube.org/latest/setup/get-started-2-minutes/)
- launch [sonar-scanner](https://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner) on the project 
- go to localhost:9000 and check content:

Configure Sonar #26

---

CHANGELOG.md

issue #28 - updating changelog for 0.0.3 release

---

CHANGELOG.md
package-lock.json
package.json
src/extension.ts
src/test/wsdl_url.test.ts

issue #36 - fixing problem with processing wsdl from url

---

CHANGELOG.md
Readme.md
package.json

updating version to 0.0.6

---

package-lock.json
package.json

updating version to 0.0.7 after releasing 0.0.6

---

wsdl2rest/pom.xml

issue #44 - updating wsdl2rest version to 0.8.0.fuse-730090

---

Readme.md

Signed-off-by: mflinn <mflinn@redhat.com>

fixed formatting

---

CHANGELOG.md
package-lock.json
package.json

issue #46 - updating to 0.0.8, updating changelog, fixing package audit

---

CHANGELOG.md
package-lock.json
package.json
wsdl2rest/.settings/org.eclipse.jdt.core.prefs
wsdl2rest/pom.xml

updating to latest Fuse 7.3 versions for issue #49

---

CHANGELOG.md
package-lock.json
package.json

update to 0.0.9 for next release after releasing 0.0.8 tag

---

CHANGELOG.md

Add move to Red Hat publisher in changelog #54

---

CHANGELOG.md
package-lock.json
package.json

Prepare next iteration 0.0.10

---

Contributing.md
Jenkinsfile

to allow whole team to do a release

Add whole team to submitter list #54

---

.travis.yml

as Travis modified the way it can be used

Fix xvfb for Travis build #61

---

CHANGELOG.md
Readme.md
package.json

Update to name approved by Red Hat legal department #59

---

CHANGELOG.md
package-lock.json
package.json

prepare next iteration release 0.0.11

---

.travis.yml

Exclude dependabot branches from non-PR jobs #92

---

package.json

Fix Author field #123

---

package-lock.json
package.json
src/test/index.ts
src/test/runTest.ts

see https://code.visualstudio.com/api/working-with-extensions/testing-extension#migrating-from-vscode

FUSETOOLS2-20 - Use newer VS Code test framework

---

.travis.yml
CHANGELOG.md
wsdl2rest/pom.xml

FUSETOOLS2-188 - Upgrade wsdl2rest to publicly released version

---

CHANGELOG.md
package-lock.json
package.json

Prepare next development iteration 0.0.12

---

package-lock.json
package.json

Signed-off-by: bfitzpat@redhat.com <bfitzpat@redhat.com>

Bumping @types/vscode from 1.41.0 to 1.42.0 and updating engine version

---

package-lock.json
package.json

Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>

upgrade vscode to 1.44.0

---

.gitignore
.vscodeignore
package.json
src/ui-test/extension.all.test.ts
src/ui-test/install.test.ts
src/ui-test/uitest_runner.ts

Signed-off-by: Marian Lorinc <mlorinc@redhat.com>

FUSETOOLS2-91 - Add UI Tests for extension installation

---

CHANGELOG.md
wsdl2rest/pom.xml

FUSETOOLS2-609 - use Fuse 7.7 wsdl2rest version

---

Readme.md

FUSETOOLS2-825 - update badge for Travis moving from .org to .com

---

.circleci/config.yml
Jenkinsfile

relates https://gitlab.cee.redhat.com/codeready-studio/cci-config/-/merge_requests/461
need to update branch name in Github web Ui before merging

FUSETOOLS2-1296 - migrate master to main branch

---

CHANGELOG.md
package-lock.json
package.json

prepare next development iteration 0.0.15

---

CHANGELOG.md
wsdl2rest/pom.xml

FUSETOOLS2-1405 - upgrade internal wsdl2rest to Fuse 7.10
